-- PostgreSQL Compatibility: Remove H2-specific UUID defaults
-- UUIDs are now generated by the application (UUID.randomUUID())
--
-- Note: This migration has no actual ALTER statements because:
-- 1. V1 and V3 were updated to remove RANDOM_UUID() defaults
-- 2. For existing databases, the application already generates UUIDs
-- 3. This migration exists only to document the compatibility fix
--
-- Changes made to migrations:
-- - V1: Removed DEFAULT RANDOM_UUID() from boards.id and tasks.id
-- - V3: Changed TIMESTAMP WITH TIME ZONE to TIMESTAMP (H2 compatibility)
--
-- Application changes:
-- - BoardService.createBoard(): Now sets id = UUID.randomUUID()
-- - TaskService.createTask(): Now sets id = UUID.randomUUID()
-- - BacklogCategoryService.create(): Already sets id = UUID.randomUUID()

-- This is a no-op migration to record the schema state
SELECT 1 WHERE 1=0;
